on:
  pull_request:
  push:
      branches: gg_kp

jobs:
    assemble:
      strategy:
        matrix:
          version: ["gg_kp","gg_kp_2"]
      runs-on: "ubuntu-latest"
      steps:
         - uses: actions/checkout@v3
         - id: foo
           uses: cdsap/ge-experiment-runner@v.1.2
           with:
             task: "assembleDebug"
             iterations: 5
             experiment-id: ${{github.run_number}}
             variant: ${{ matrix.version }}
             class: "core/data/src/main/java/com/google/samples/apps/nowinandroid/core/data/repository/NewsRepository.kt"
             api-key: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

    reportAssemble:
      runs-on: "ubuntu-latest"
      needs: [ assemble]
      steps:
         - uses: actions/checkout@v3
         - id: fooa
           uses: cdsap/ge-experiment-report@v.1.2
           with:
             task: "assembleDebug"
             max-builds: 999
             experiment-id: ${{github.run_number}}
             tags: "gg_kp, gg_kp_2"
             project: "nowinandroid"
             api-key: ${{ secrets.GE_API_KEY }}
             url: ${{ secrets.GE_URL }}
             gh_token: ${{secrets.GITHUB_TOKEN}}
